# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfdtunnel < Formula
  desc "Use multiple cloudflared tunnel instances on the fly"
  homepage "https://github.com/mmiranda/cfdtunnel"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmiranda/cfdtunnel/releases/download/v0.1.1/cfdtunnel_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "87e60f1efbb573c3869091e229314c5d3d56c1507750e47916326e7f76231185"

      def install
        bin.install "cfdtunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmiranda/cfdtunnel/releases/download/v0.1.1/cfdtunnel_0.1.1_Darwin_arm64.tar.gz"
      sha256 "11ce263637b464a7e8aa975e5b73ebab89bac19cfd258cac2923177ddd4fc2f6"

      def install
        bin.install "cfdtunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mmiranda/cfdtunnel/releases/download/v0.1.1/cfdtunnel_0.1.1_Linux_x86_64.tar.gz"
      sha256 "0b3d8256e11060d3653a593ac805a0a432500d40c5c5de1adb51bfed794289e6"

      def install
        bin.install "cfdtunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmiranda/cfdtunnel/releases/download/v0.1.1/cfdtunnel_0.1.1_Linux_arm64.tar.gz"
      sha256 "8a1fdc5fa0f5fdbbed22c47df18356ab343e7423fbd843f26431ba00a04de016"

      def install
        bin.install "cfdtunnel"
      end
    end
  end

  test do
    system "#{bin}/program", "version"
  end
end
