# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cfdtunnel < Formula
  desc "Use multiple cloudflared tunnel instances on the fly"
  homepage "https://github.com/mmiranda/cfdtunnel"
  version "0.1.0-rc"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmiranda/cfdtunnel/releases/download/v0.1.0-rc/cfdtunnel_0.1.0-rc_Darwin_x86_64.tar.gz"
      sha256 "966ca32a68d3495552eb559762639bad30ef8a71ea8b7bc9a25e1c1cbc4aadd7"

      def install
        bin.install "cfdtunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmiranda/cfdtunnel/releases/download/v0.1.0-rc/cfdtunnel_0.1.0-rc_Darwin_arm64.tar.gz"
      sha256 "66a7dd92dd890462175195643d007603eca58c6ef541fbb028417db4cca9c59d"

      def install
        bin.install "cfdtunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmiranda/cfdtunnel/releases/download/v0.1.0-rc/cfdtunnel_0.1.0-rc_Linux_arm64.tar.gz"
      sha256 "4b1912628f6336d75ef2b7aa72a0d4d0febf3de8f5995ffa68ce48b22dfe1029"

      def install
        bin.install "cfdtunnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mmiranda/cfdtunnel/releases/download/v0.1.0-rc/cfdtunnel_0.1.0-rc_Linux_x86_64.tar.gz"
      sha256 "e33b6b44746a2827e0b989286f46fcf33f1cab1ade5401666e1a2f7e26a352bb"

      def install
        bin.install "cfdtunnel"
      end
    end
  end

  test do
    system "#{bin}/program", "--version"
  end
end
