# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MarkdownIndex < Formula
  desc "Tool to generate a global Markdown Summary Index based on other markdown files"
  homepage "https://github.com/mmiranda/markdown-index"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.1/markdown-index_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "2b878934337bc0bc61fb4f8422479dbf1dcaaff6d7f4ef624194f0eed6ea9733"

      def install
        bin.install "markdown-index"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.1/markdown-index_0.1.1_Darwin_arm64.tar.gz"
      sha256 "0547ab3f71b06bee78b470f4d3b8f2cd67295a7711b9fb71a30ba5cda3261563"

      def install
        bin.install "markdown-index"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.1/markdown-index_0.1.1_Linux_x86_64.tar.gz"
      sha256 "a419b873bf6056eb9f50407fdb0a5e3f7a8c8a7e23ac8030eaa372b186eeec58"

      def install
        bin.install "markdown-index"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.1/markdown-index_0.1.1_Linux_arm64.tar.gz"
      sha256 "f378dc3b938e90947d2cd76c89293d7b427f9efd8bb4fa94cd1bddcbb9880133"

      def install
        bin.install "markdown-index"
      end
    end
  end

  test do
    system "#{bin}/program", "version"
  end
end
