# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MarkdownIndex < Formula
  desc "Tool to generate a global Markdown Summary Index based on other markdown files"
  homepage "https://github.com/mmiranda/markdown-index"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.2/markdown-index_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "9ed7b666b53b1b7ef345a0c313e3ff02233a1464074c30c2c42172a75f0f4a7a"

      def install
        bin.install "markdown-index"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.2/markdown-index_0.1.2_Darwin_arm64.tar.gz"
      sha256 "2d8ed8a386abe5b10afa10bbe9498188f84a0b8d4ba998e533b9d869acab2131"

      def install
        bin.install "markdown-index"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.2/markdown-index_0.1.2_Linux_x86_64.tar.gz"
      sha256 "e5c18e13f65db2fc97dafc2bccd13e4485a57221cf072d929ef58279c5e082d2"

      def install
        bin.install "markdown-index"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.2/markdown-index_0.1.2_Linux_arm64.tar.gz"
      sha256 "01a42ca99a7725d078d34f4181b4ff0fa90fc2e26c28dc9905713d06110a0108"

      def install
        bin.install "markdown-index"
      end
    end
  end

  test do
    system "#{bin}/program", "version"
  end
end
