# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MarkdownIndex < Formula
  desc "Tool to generate a global Markdown Summary Index based on other markdown files."
  homepage "https://github.com/mmiranda/markdown-index"
  version "0.1.1-alpha"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.1-alpha/markdown-index_0.1.1-alpha_Darwin_x86_64.tar.gz"
      sha256 "4b572755c04ac1b8fc85321252539e3db7aa56a8b82c28d7be26bda28c924c57"
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.1-alpha/markdown-index_0.1.1-alpha_Darwin_arm64.tar.gz"
      sha256 "332083e880235d87da20fb420c20aaca62148796dd9b4a94f0fc03251b658c50"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.1-alpha/markdown-index_0.1.1-alpha_Linux_arm64.tar.gz"
      sha256 "44cbd57f690a074871477a1b743090a806b466071768790ac59797a1efa2876a"
    end
    if Hardware::CPU.intel?
      url "https://github.com/mmiranda/markdown-index/releases/download/v0.1.1-alpha/markdown-index_0.1.1-alpha_Linux_x86_64.tar.gz"
      sha256 "bc9536a475f12b5adbbeb6fb972b95b3a99b1d4cdc50421f26817f0e397a9e34"
    end
  end

  def install
    bin.install "markdown-index"
  end

  test do
    system "#{bin}/program", "version"
  end
end
